-- Jalankan seluruh file ini di Supabase Dashboard > SQL Editor.

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    display_name text not null default '',
    email text not null default '',
    avatar_url text not null default '',
    updated_at timestamptz not null default now()
);

create table if not exists public.conversations (
    id uuid primary key default gen_random_uuid(),
    user_one uuid not null references auth.users(id) on delete cascade,
    user_two uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz not null default now(),
    constraint conversations_different_users check (user_one < user_two),
    constraint conversations_unique_pair unique (user_one, user_two)
);

create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    conversation_id uuid not null references public.conversations(id) on delete cascade,
    sender_id uuid not null references auth.users(id) on delete cascade,
    receiver_id uuid not null references auth.users(id) on delete cascade,
    body text not null check (char_length(body) between 1 and 2000),
    created_at timestamptz not null default now()
);

create index if not exists messages_conversation_created_at_idx
    on public.messages (conversation_id, created_at);

alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;

drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles"
    on public.profiles for select
    to authenticated
    using (true);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
    on public.profiles for insert
    to authenticated
    with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
    on public.profiles for update
    to authenticated
    using (auth.uid() = id)
    with check (auth.uid() = id);

drop policy if exists "Participants can read conversations" on public.conversations;
create policy "Participants can read conversations"
    on public.conversations for select
    to authenticated
    using (auth.uid() = user_one or auth.uid() = user_two);

drop policy if exists "Users can create conversations they join" on public.conversations;
create policy "Users can create conversations they join"
    on public.conversations for insert
    to authenticated
    with check (auth.uid() = user_one or auth.uid() = user_two);

drop policy if exists "Participants can read messages" on public.messages;
create policy "Participants can read messages"
    on public.messages for select
    to authenticated
    using (
        exists (
            select 1
            from public.conversations
            where conversations.id = messages.conversation_id
                and (
                    auth.uid() = conversations.user_one
                    or auth.uid() = conversations.user_two
                )
        )
    );

drop policy if exists "Participants can send messages" on public.messages;
create policy "Participants can send messages"
    on public.messages for insert
    to authenticated
    with check (
        sender_id = auth.uid()
        and receiver_id <> sender_id
        and exists (
            select 1
            from public.conversations
            where conversations.id = messages.conversation_id
                and (
                    (
                        conversations.user_one = sender_id
                        and conversations.user_two = receiver_id
                    )
                    or (
                        conversations.user_one = receiver_id
                        and conversations.user_two = sender_id
                    )
                )
        )
    );

-- Aktifkan realtime untuk pesan. Aman dijalankan ulang.
do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
            and schemaname = 'public'
            and tablename = 'messages'
    ) then
        execute 'alter publication supabase_realtime add table public.messages';
    end if;
end;
$$;
